### ISSUE TITLE
Doesn't appear to support images

### ISSUE THREAD

**Issue by nevir** [mjohnston/react-native-webpack-server#107]
It looks like RN changed `require('image!name')` to return an integer now (as of 0.11). However, asset management also appears to be getting an even larger overhaul:
- https://github.com/facebook/react-native/pull/3545 
- https://github.com/facebook/react-native/pull/3523

**Comment by frantic** [comment]
That's right. Both new `require('./your_image.png')` and old `require('image!your_image')` are going to return opaque integer ID of the resource. `<Image />` and other components know how to deal with it already. Do you have a use case where you'd need more information about the image that's being loaded?

**Comment by nevir** [comment]
Currently, `react-native-webpack-server` returns `{uri: 'something', static: true}` (the pre-0.11 RN format)

**Comment by frantic** [comment]
Old format should be still supported by `<Image />`

**Comment by nevir** [comment]
Yup! Was a problem on my end
