### ISSUE TITLE
Not respecting port with `isPackagerRunning`

### ISSUE THREAD

**Issue by niftylettuce** [mjohnston/react-native-webpack-server#114]
Per https://github.com/facebook/react-native/blob/7e53ee1095ac956887dd6a20d19a403096472660/private-cli/src/util/isPackagerRunning.js#L23 it doesn't respect the port you can pass with the flags on CLI

**Comment by niftylettuce** [comment]
For example, if I run my script with this:

``` bash
react-native-webpack-server start -e index.android -P 9090 -p 9091 -w 9092
```

Then `react-native run-android` won't work since it is looking for port 8080.

**Comment by elliottsj** [comment]
This is a known issue with react-native: https://github.com/facebook/react-native/issues/1429

Unfortunately there are a bunch of places in RN where port 8081 is hard-coded; until that's resolved, you'll need to just use port 8081

**Comment by niftylettuce** [comment]
See https://github.com/mjohnston/react-native-webpack-server/issues/65#issuecomment-151222398 I did a quick hack
