### ISSUE TITLE
Use of ES6 syntax in webpack config

### ISSUE THREAD

**Issue by niftylettuce** [mjohnston/react-native-webpack-server#119]
It doesn't parse!  It gives error, e.g.:

```
import path from 'path';
^^^^^^

SyntaxError: Unexpected reserved word
```

**Comment by elliottsj** [comment]
If you want to use import statements (and a bunch of other ES6 features) in node you'll need to use babel-node: `npm install babel`, then:

``` shell
./node_modules/.bin/babel-node ./node_modules/.bin/rnws start
```

**Comment by niftylettuce** [comment]
Didn't know this!  Thanks!
