### ISSUE TITLE
BabelES6 example fails with 'RCTRootView.h not found'

### ISSUE THREAD

**Issue by jsierles** [mjohnston/react-native-webpack-server#12]

**Comment by jsierles** [comment]
Fixed this by re-adding the React library - in the existing project a few files are not included in the source compilation list.

Another issue, when running 'hot' an error pops up: undefined is not an object, evaluating 'navigator.userAgent.match'

**Comment by mjohnston** [comment]
You have to `npm install` inside each example directory to pull in the React Native sources. As for the second issue, React hot loader only works with the web socket or WebView executors.

See the [docs](https://github.com/mjohnston/react-native-webpack-server/blob/master/Examples/BabelES6/README.md) for the example project for more info.

**Comment by jsierles** [comment]
Cheers, looking good now!

**Comment by ashishonmobile** [comment]
is there any way we can save all the react native sources so we do not need to download it always via npm install

Please help.

**Comment by theKaren** [comment]
ashishonmobile, seem not unfortunately. :(
