### ISSUE TITLE
Add platform-dependent module resolution

### ISSUE THREAD

**Issue by elliottsj** [mjohnston/react-native-webpack-server#120]
As described by @philikon in https://github.com/mjohnston/react-native-webpack-server/pull/111#discussion_r43030879:

> Another thing to consider is the platform-based module resolution. If I do `require('./foobar')` with the React Native packager within a bundle that's been loaded with `?platform=<platform>`, it will resolve to `./foobar.<platform>.js` or `./foobar.js`. Having both `foobar.ios.js` and `foobar.android.js` being importable as `./foobar` is quite powerful. Because you can push platform-dependent differences into their own modules/React components and the code that's common to both platforms simply imports the module/component while being oblivious to which platform it's actually running on.

As far as I know, webpack does not support serving multiple configurations (i.e. both Android and iOS) in the same process, so we'll need to run two webpack instances to have different module resolution rules for each platform.

**Comment by balthazar** [comment]
@elliottsj Any updates on this? It seems pretty important to me!

**Comment by balthazar** [comment]
Didn't catch #143, my bad.

**Comment by philikon** [comment]
> As far as I know, webpack does not support serving multiple configurations (i.e. both Android and iOS) in the same process, 

Fortunately that's not true! Webpack's multicompiler feature makes this easily possible. Here's how I have solved this for myself: https://github.com/mjohnston/react-native-webpack-server/pull/156#issuecomment-195826035
