### ISSUE TITLE
error: unknown option `-e'

### ISSUE THREAD

**Issue by niftylettuce** [mjohnston/react-native-webpack-server#122]
> App@0.0.1 start-android-webpack-server /Users/nexus/Public/foobar/Foobar
> react-native-webpack-server start -e index.android -P 9090 -p 9091 -w 9092

  error: unknown option `-e'

**Comment by niftylettuce** [comment]
I'm on the 0.12-hmr

**Comment by niftylettuce** [comment]
These all happened after your rebase to master or whatever on this branch

**Comment by jforaker** [comment]
+1

**Comment by niftylettuce** [comment]
It's --androidEntry now

**Comment by elliottsj** [comment]
Yep, separate `--iosEntry` and `--androidEntry` options now.
