### ISSUE TITLE
Requiring react-native modules inside node_modules fails

### ISSUE THREAD

**Issue by mjohnston** [mjohnston/react-native-webpack-server#13]

**Comment by amccloud** [comment]
Were you able to reproduce? If not I can setup an example project.

**Comment by mjohnston** [comment]
Yeah I am - I think there are a couple things going on here... still investigating.

**Comment by mjohnston** [comment]
Here's what I found:
1. Babel will throw an error when you try to `require("React")` (note uppercase React). I filed a a bug here: https://github.com/babel/babel/issues/1366
2. The generated webpack externals were not including modules inside react-tools, e.g. `ReactPropTypes`. I pushed a fix here: https://github.com/mjohnston/react-native-webpack-server/commit/f30d1aabad05e05e4e081249a951cf11210698cb

I was able to work around the first issue by commenting out the relevant validation code in `node_modules/babel-core/lib/babel/transformation/transformers/validation/react.js`.

**Comment by mjohnston** [comment]
I'll leave this issue open until we have a resolution for the referenced Babel issue.

**Comment by mjohnston** [comment]
@amccloud Looks like you can blacklist the react validation. I added it to the webpack config in the example project: https://github.com/mjohnston/react-native-webpack-server/commit/55df1c405093b9b7ea5d1ccf1aaaee0331aee2b5

Let me know if that works for you.

**Comment by mjohnston** [comment]
Tested on master and works for me.

**Comment by amccloud** [comment]
@mjohnston Everything is working for me.

Thank you!

**Comment by mjohnston** [comment]
Great, thanks!
