### ISSUE TITLE
Unknown option: base.extra using babel-loader 6.0

### ISSUE THREAD

**Issue by JeanLebrument** [mjohnston/react-native-webpack-server#131]
Hello,

I have an error message when using `npm run hot`:  
`Unknown option: base.extra`

This is due to the `hot` option that include the following code:

```
  config.module.loaders[0].query.extra = {
    'react-transform': {
      transforms: [{
        transform: 'react-transform-hmr',
        imports: ['react-native'],
        locals: ['module']
      }]
    }
  };
```

Any suggestion? 

Thanks!

**Comment by elliottsj** [comment]
[babel-plugin-react-transform](https://github.com/gaearon/babel-plugin-react-transform) does not yet support Babel 6. See https://github.com/gaearon/babel-plugin-react-transform/issues/46

**Comment by catamphetamine** [comment]
@elliottsj Now it does
