### ISSUE TITLE
Android won't run - Invariant Violation

### ISSUE THREAD

**Issue by Ehesp** [mjohnston/react-native-webpack-server#132]
I've pulled the repository example https://github.com/mjohnston/react-native-webpack-server/tree/master/Examples/BabelES6

Followed the instructions, however once the app starts on the emulator I get the following error:

![image](https://cloud.githubusercontent.com/assets/842078/11002988/17801d8c-84a8-11e5-9f8f-6f2956b2cb61.png)

Node: 5.0.0
NPM: 3.3.6

I've tried a full reinstall of Node & NPM so this is not the issue.

Chrome Debugger shows the following error too:

![image](https://cloud.githubusercontent.com/assets/842078/11003124/a9a967fe-84a8-11e5-9f00-c58589bb779d.png)

Related to https://github.com/jhabdas/react-native-webpack-starter-kit/issues/11

**Comment by Salakar** [comment]
+1 - Getting the same issue here.

![image](https://cloud.githubusercontent.com/assets/5347038/11003612/6008a6fc-84ab-11e5-9e04-bf83073715b4.png)

**Comment by Salakar** [comment]
Turns out it was setting the debug server that did the trick, as per https://github.com/mjohnston/react-native-webpack-server#setup  - woops. Feel free to close when @Ehesp confirms working.

**Comment by EvHaus** [comment]
I have the same problem as the original post, and setting the dev server to "localhost" doesn't help. Instead I now get "Unable to download JS bundle. Did you forget to start the development server or connect your device?" error.

I'm on Windows 10, running Android emulator via Genymotion using react-native 0.15.0-rc and rnws 0.8.2-rc.

**Comment by Salakar** [comment]
You need open another cmd window and have 'npm run start' running.

**Comment by EvHaus** [comment]
@Salakar Hmm. I do have the webpack + react-native server running via `set HOT=1 && rnws start --hot". Is that what you mean?
