### ISSUE TITLE
New react-native projects with same setup as in the BabelES6 example fails to build.

### ISSUE THREAD

**Issue by jrm2k6** [mjohnston/react-native-webpack-server#142]
Steps to reproduce:

`react-native init MyProject`

Copy from BabelES6 example:
- package.json
- webpack.config.js

Starting the webpack dev server and building in XCode after doing the port modification will fail with 
'no index.ios.js file found in any of the roots'

Copying the content of the BabelES6 example in the newly created project will work just fine.

```
 jrm2k6  ~/Workspace/Perso  react-native -v
0.1.7
 jrm2k6  ~/Workspace/Perso  node -v
v4.1.2
```

**Comment by ghost** [comment]
Perhaps this may help @jrm2k6 https://github.com/jhabdas/react-native-webpack-starter-kit. It's a similar project I maintain and includes ESLint and some starter patterns.

**Comment by philikon** [comment]
0.8.3 ships with RN 0.17 support and a revamped BabelES6 example. I'm going to close this. Please reopen if you continue to see problems.
