### ISSUE TITLE
Node v5

### ISSUE THREAD

**Issue by oliviertassinari** [mjohnston/react-native-webpack-server#149]
Any reason here https://github.com/mjohnston/react-native-webpack-server/blob/master/package.json#L39 for using

``` json
  "engines": {
    "node": "^4.0.0"
  },
```

instead of 

``` json
  "engines": {
    "node": ">=4"
  },
```

?

**Comment by philikon** [comment]
No strong reason. I'm not a big fan of over-restrictive version constraints, so I'd be happy with `">=4"`. Feel free to submit a PR.

Does Node 5 actually work? Afaik Node 5 ships with npm 3 and so far I don't think RN officially supports npm 3. But of course it may work anyway. In any case, Node 4 is an LTS release whereas Node 5 is a "bleeding edge" release (https://nodejs.org/en/blog/community/node-v5/), so Node 4 should remain the strongly recommended version for now IMHO.

**Comment by balthazar** [comment]
Testing it on 5.7 and don't have any issue at the moment ;)

**Comment by ghost** [comment]
@philikon This can be labeled question or closed.

**Comment by philikon** [comment]
Thanks! Like I said, happy to entertain a PR that lifts the upper Node version boundary, and perhaps adds Node 5 to the unit test matrix.
