### ISSUE TITLE
node core modules?

### ISSUE THREAD

**Issue by mvayngrib** [mjohnston/react-native-webpack-server#15]
first of all, thanks for making this library!

This may be a naive question as I'm not that familiar with webpack, but how would you use node core modules (or rather their browserified versions)? I see node-libs-browser under webpack, but I'm not sure how to make webpack include them in the bundle. Adding something like...

``` js
var path = require('path')
```

...to App.js results in the red screen with:

```
Requiring unknown module "path".
If you are are sure the module is there, try restarting the packager.
```

If it helps, in the console where I ran the webpack server, I see: 

```
           Asset     Size  Chunks             Chunk Names
    index.ios.js  18.1 kB       0  [emitted]  index.ios
index.ios.js.map  18.4 kB       0  [emitted]  index.ios
chunk    {0} index.ios.js, index.ios.js.map (index.ios) 15.6 kB [rendered]
    [0] multi index.ios 28 bytes {0}
    [1] ./src/main.js 468 bytes {0}
    [2] external "React" 42 bytes {0} [not cacheable]
    [3] ./src/components/App.js 2.85 kB {0} [built]
    [4] ./src/data/docs.js 3.35 kB {0}
    [5] ./src/components/DocIndex.js 6.1 kB {0}
    [7] ./src/components/DocSection.js 2.74 kB {0}
   [92] external "path" 42 bytes {0} [not cacheable]
webpack: bundle is now VALID.
```

**Comment by mjohnston** [comment]
Hmm, this could just be a case of the React Native externals extractor being over-aggressive, crawling into node_modules (perhaps react-tools' node_modules).

**Comment by mvayngrib** [comment]
yea, i noticed it also breaks on some deps from npm, such as "foreach"

**Comment by mjohnston** [comment]
I left a comment in the PR which I **think** should work. Webpack will build in the node core libs from browserify by default - you shouldn't have to do anything. For more granular control over this see the webpack docs: http://webpack.github.io/docs/configuration.html#node

**Comment by mvayngrib** [comment]
i was thinking it would be good to have fs, dgram, dns and net available, as there are already node API compatible shims for most of these for react-native. Is this something people are interested in? I'm currently using a [fork](https://github.com/mvayngrib/react-native-node-libs) of node-libs-browser, and a fork of [webpack](https://github.com/mvayngrib/webpack) that allows use of an alt node-libs-browser to make that happen. I opened an [issue](https://github.com/webpack/node-libs-browser/issues/27) about making the node-libs-browser usage more flexible, but no one has responded yet.
