### ISSUE TITLE
global var window consistency

### ISSUE THREAD

**Issue by mvayngrib** [mjohnston/react-native-webpack-server#18]
this is a webpack config issue it seems, due to its defaulting to "target: web". However changing to "target: node" results in other problems so...

Symptom: "window" as a global exists whether or not DevTools is open and debugging, however it has different properties. For example, with DevTools open, it has "crypto", but with DevTools closed, it does not. This obviously makes for inconsistent (if amusing) app behavior.

In my particular case, I'm using the brorand, an rng wrapper that checks for a global "window" var to decide which crypto implementation to use. The result is that if I have DevTools open, it successfully uses window.crypto.getRandomValues, but when it's closed, it sees "window", thinks it's in the browser, but doesn't see window.crypto and gives up with a "Not implemented" error.

(with the regular react-native packager, there is no window global var)

**Comment by mjohnston** [comment]
Are you sure about the last statement? It looks like react-native will always define a `window` object if it doesn't exist: https://github.com/facebook/react-native/blob/master/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js#L32

It's possible it's just an order of execution quirk - with RN packager, the brorand code might be executed before the JS environment is shimmed, whereas with webpack it might be executed after (but that seems unlikely as it would cause a number of other issues in code that feature-detect on eval).

In React Native, when you run it with the default executor it uses the built-in JavaScriptCore runtime which evidently does not support a native `crypto` implementation. That is why you see different behavior with the Chrome dev tools.

**Comment by mjohnston** [comment]
Since the release target will not have native support for `window.crypto` my suggestion would be to use the browserify crypto shim in place of brorand (which is only a few lines of code).

e.g.

``` js
var crypto = require('crypto');
crypto.getRandomBytes(256);
```

**Comment by mvayngrib** [comment]
interesting, re: window, you're basically right. It depends on whether you check window before or after the require('react-native') statement. Before it, window is undefined, after it's an object.

EDIT: the above is true when using the regular packager. In yours, window is an object before "import React from 'react-native'. I'd say yours is better, being more consistent

EDIT: crypto-browserify tries to use window.crypto, so require('crypto').randomBytes(256) results in "secure random number generation not supported by this browser" from crypto-browserify/rng.js . This is an issue for react-native, I'll forward
