### ISSUE TITLE
Entry for production

### ISSUE THREAD

**Issue by auser** [mjohnston/react-native-webpack-server#19]
My webpack.config covers webpacking for development, but not yet for production. 

It'd be nice to have a plugin or pre-entry pack that includes the React native containers. 

EDIT:

To explain further, we can build a packaged jsbundle with `curl`, but would be nice to be able to build it without running the server.

With CURL:

The application is available on `http://localhost:8080/index.ios.bundle`, but when building on the packager port `http://localhost:8081/index.ios.bundle` with `curl`, the application is not bundled with the rest of the React core. Is this intended?

**Comment by mjohnston** [comment]
The idea of bundling React Native as an entry is interesting. The catch is that the entry.js passed off to the RN packager is generated based off your app's dependency tree (you can see this in the _entry directory when you're running the server). So it can't just be a static file.

There might be a better way - I'll give it some thought tonight.

**Comment by auser** [comment]
Interesting. Well, the immediate _issues_ is that using `curl` on port `8081` with the native web server doesn't actually bundle the app, it just bundles react. To bundle the full app, I have to use the built-in packager`. 

Any ideas why?

The using webpack to build the app entirely is a feature I really want and would contribute to figuring out how.

**Comment by mjohnston** [comment]
Using curl on port 8081 will talk to the packager directly - that's why it doesn't include any of your application code.

The quickest solution here would be to allow you to specify the same URL parameters the RN packager accepts (dev=false, minify=true). Then you could use curl on port 8080 to grab the minified bundle from the RN webpack server.

`curl 'http://localhost:8080/index.ios.bundle?dev=false&minify=true' -o iOS/main.jsbundle`

Would that work?

**Comment by auser** [comment]
Yeah, that would be a good interim fix, for sure.

**Comment by mjohnston** [comment]
Ok, I should be able to have something for you shortly.

**Comment by mjohnston** [comment]
@auser this is in master now if you want to give it a spin.

See: https://github.com/mjohnston/react-native-webpack-server#packaging-for-release

**Comment by auser** [comment]
Awesome. Will try now

**Comment by auser** [comment]
That works for me

**Comment by mjohnston** [comment]
Great, thanks for verifying. Will include this and the node_modules fix in a patch release.
