### ISSUE TITLE
undefined is not an object (evaluating 'navigator.userAgent.match') running examples

### ISSUE THREAD

**Issue by gaearon** [mjohnston/react-native-webpack-server#2]
Here's what I got when running Babel example with hot loader enabled:

![screen shot 2015-04-16 at 12 04 32](https://cloud.githubusercontent.com/assets/810438/7177618/c7b5546a-e430-11e4-9671-45b641e82aa5.png)

This seems to be coming from

``` js
/**
 * Check if we are running an android browser. That requires us to use
 * ArrayBuffer with polling transports...
 *
 * http://ghinda.net/jpeg-blob-ajax-android/
 */

var isAndroid = navigator.userAgent.match(/Android/i);
```

in `engine.io-parser` used by `socket.io`.

Ideas?

**Comment by gaearon** [comment]
Fixing this one gives me `document is not defined` in some other place. Is there some configuration missing?

**Comment by gaearon** [comment]
I have the same problem with the CS example.

**Comment by gaearon** [comment]
Oh, I see. I missed that part:

> NOTE: hot reload currently only works with the web socket executor (hit CMD+D in the simulator) or the WebView executor (CMD+CTRL+Z -> Enable Safari Debugging). If you regurlarly use this feature, you might want to default to the web socket exeuctor in development

**Comment by alfondotnet** [comment]
Hi @gaearon , could you provide more info on this?: 

>  If you regurlarly use this feature, you might want to default to the web socket exeuctor in development

How to do that?,
Cheers!

**Comment by alfondotnet** [comment]
Oh, it's ok, I found it: https://github.com/mjohnston/react-native-webpack-server#hot-reload
