### ISSUE TITLE
Pulled down Examples, ran Babel example, no hot loading or live reload

### ISSUE THREAD

**Issue by jkatsnelson** [mjohnston/react-native-webpack-server#20]
Hey there,

I've had no luck getting this to work.

I configured my own project to use the same set up as the babel example, and while i got it compiling fine, it was only with manual refresh. I set up "hot", tried live reload, nothing worked.

I tried pulling down your example and running that as well. Also got it running, but no hot loading was happening. I am pretty sure I followed your instructions to a T, and I am using a typical stock mac set up...I run a lot of node projects already, so weird dependency problems seem unlikely.

Feel free to close this, since I know this isn't a ton of detail, just wanted you to know

**Comment by mjohnston** [comment]
Could you provide more detail as to what breaks when you enable hot reload? Do you get a compilation error from webpack? If you could include logs that identify the breakage that would be great.

**Comment by robertjpayne** [comment]
@mjohnston same issue here.

Webpack picks up the changes and compiles fine, the react-native packager transforms them fine too but the native bridge never updates.

**Comment by robertjpayne** [comment]
@mjohnston maybe it's an issue with latest react-native 0.4.2?

**Comment by robertjpayne** [comment]
@mjohnston @jkatsnelson  sorry for a bit of issue spam, I've managed to get it working:
- You must use `npm run-script hot` if you're basing your `package.json` off of the example project.
- The main entry file cannot be hot-loaded so make sure you just import stuff into the entry file and register it with react-native's AppRegistry

**Comment by mjohnston** [comment]
@robertjpayne Thanks for the clarification. That's correct - components that you want to be hot loaded cannot live in the entry file.
