### ISSUE TITLE
Bug with 0.4.3 with requiring

### ISSUE THREAD

**Issue by auser** [mjohnston/react-native-webpack-server#22]
Not sure exactly how to solve this, but with the latest version of RN the webpack server cannot find the `NavigatorNavigationBarStyles` or the `StaticContainer.react` library.

**Comment by mjohnston** [comment]
I think I have an idea what's going on. Should have a fix shortly.

**Comment by mjohnston** [comment]
@auser this should work on master now. Let me know otherwise.

**Comment by auser** [comment]
Yep, that fixes it. 

Thanks!

**Comment by robertjpayne** [comment]
@mjohnston mind publishing an update to npm? Would be appreciated!

**Comment by robertjpayne** [comment]
Also doesn't seem like the hot loader support has been fixed.

**Comment by mjohnston** [comment]
@robertjpayne Yes, coming right up.

I don't want to break existing projects that are locked in to react-native 0.4.3 and below. So I'll publish 2 updates to npm:
- 0.1.x for react-native <0.4.3
- 0.2.x for react-native >=0.4.3
