### ISSUE TITLE
SourceMaps don't work properly when hot loading using devtool: 'eval'

### ISSUE THREAD

**Issue by skevy** [mjohnston/react-native-webpack-server#27]
Source maps work perfectly when not using the hot loader...but when using the hot loader, two things happen:

1) index.ios.map is not served at http://localhost:8080/, as it is when hot loading is not enabled.
2) Gives right source location for my code, but not for React code (obviously related to number 1): 
![image of error](https://s3.amazonaws.com/f.cl.ly/items/2g0s0B0M38290G2w200T/Screen%20Shot%202015-05-17%20at%203.25.22%20PM.png)
3) When you click on either my code or React Native code in the red screen of death in the simulator, it doesn't open the location in the editor as it does when hot loading is not enabled.

I haven't dove into your code yet to see why this might be happening, but I thought I'd post an issue here in case you had a quick fix.

Great project! So nice to be able to use webpack, esnext, etc. with React Native!

**Comment by skevy** [comment]
To clarify after a bit more investigation...

This doesn't really have to do with hot reloading at all...it has to do with using anything but "source-map" as the webpack dev tool...which make sense. I'm not sure if there's a way to make the normal source map from the packager and the eval source map from `devtool: eval` play nice together.

**Comment by mjohnston** [comment]
Yeah, the example projects are set up to use `devtool: eval` for faster incremental builds when hot loading is turned on. I'm not sure if there is a way to make the eval source map and hot loader work together.

Pinging @gaearon :)

**Comment by gaearon** [comment]
> I'm not sure if there is a way to make the eval source map and hot loader work together.

Hot loader works with any devtool.

**Comment by skevy** [comment]
To be clear, I'm not saying that hot loader doesn't work (it works fine)...I'm saying that the concatenation of source maps don't work when using devtool eval. That of course makes sense...I'm just flagging the problem.

I plan to look into this this week if you don't get to it first. :)

**Comment by mjohnston** [comment]
Ah, got it. Let me know if you get a chance to look into it. I don't think I will be able to get to it this week.
