### ISSUE TITLE
React Dev Tools don't work when hot is enabled

### ISSUE THREAD

**Issue by skevy** [mjohnston/react-native-webpack-server#28]
React Dev Tools show no components when hot loading is enabled, but run fine without hot loading.

**Comment by mjohnston** [comment]
To be honest, I'm not that familiar with the React dev tools. But my understanding is that it relies on `React` being defined in the global scope. If that's the case, it should just work: https://github.com/mjohnston/react-native-webpack-server/blob/master/lib/Server.js#L16

(global is either the mocked global object inside the default context executor, or window in the webview or websocket executors)

I'll have to dig further on this one but it might be a couple days. A PR would be greatly appreciated if you're so inclined :)

**Comment by gaearon** [comment]
I just tried the new React DevTools with React Native Webpack Server 0.5.0 with hot reloading enabled, and they seem to work fine. May be related to [our switch to React Transform](github.com/mjohnston/react-native-webpack-server/pull/64), the new React DevTools, or both.

Shall we close?

<img width="766" alt="screen shot 2015-09-18 at 02 55 03" src="https://cloud.githubusercontent.com/assets/810438/9948971/e6d0d55a-5db0-11e5-9551-ab1fae2d0a4e.png">
