### ISSUE TITLE
Can't build the example projects with Xcode

### ISSUE THREAD

**Issue by gaearon** [mjohnston/react-native-webpack-server#30]
I tried 0.2.0, but I'm getting this error with Xcode now:

![screen shot 2015-05-28 at 3 27 11](https://cloud.githubusercontent.com/assets/810438/7850344/a622c1d2-04e9-11e5-9334-c26be64f7000.png)

This appears related to some changes in RN 0.4.4, but I have no idea what to do :-(

**Comment by gaearon** [comment]
All right, the fix apparently is to [change the linked project](https://github.com/facebook/react-native/issues/1290#issuecomment-102786546).

**Comment by mjohnston** [comment]
Thanks @gaearon for the heads up. There appear to have been some breaking changes in 0.4.x - I need to update the examples.
