### ISSUE TITLE
Using from a remote simulator

### ISSUE THREAD

**Issue by jsierles** [mjohnston/react-native-webpack-server#32]
For rnplay.org, we have a simulator running inline from appetize.io: https://rnplay.org/plays/yQ2fnQ

Would it be possible to use this server from appetize (or a device) when running the webpack server on a remote host?

**Comment by mjohnston** [comment]
This should work. Have you tried changing the webpack config and the entry point in the RN project's AppDelegate to reference a remote host?

**Comment by jsierles** [comment]
The appdelegate loads from the remote host - but wouldn't using the websocket executor for hot reload be out of the question since there's no browser to run it on?

**Comment by mjohnston** [comment]
Hot reload also works with the webview executor.

**Comment by jsierles** [comment]
Ah, so this would work! Last thing - would restarting the server break the hot reload state? We'd need to restart it when new entry points are added.

**Comment by mjohnston** [comment]
Hm I would guess so. You might want to use one of the example projects to simulate that scenario first.
