### ISSUE TITLE
examples not work with options.root.forEach(function(root) {^ TypeError: undefined is not a function

### ISSUE THREAD

**Issue by movever** [mjohnston/react-native-webpack-server#33]
when i ran `npm start`,throw errors as follow

```
webpack: bundle is now VALID.
/Users/macbook/workspace/rui/native/react-native-webpack-server/Examples/CoffeeScript/node_modules/react-native/packager/packager.js:71
    options.root.forEach(function(root) {
                 ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/macbook/workspace/rui/native/react-native-webpack-server/Examples/CoffeeScript/node_modules/react-native/packager/packager.js:71:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by Nek** [comment]
I've got the same problem.

**Comment by Nek** [comment]
I've fixed the problem by downgrading react-native from 0.5.0 to 0.4.3.

**Comment by grabbou** [comment]
Same here. 0.4.4 works w/o issues.

**Comment by amccloud** [comment]
This is an issue with react-native 0.5.0 and appears to be fixed in 0.6.0/master.

**Comment by grabbou** [comment]
Are you 100% sure? Sounds weird that nobody reported that issue before

**Comment by amccloud** [comment]
Yes. It happened specifically when using the --root option on the packager.

Can be reproduced with out react-native-webpack-server

``` sh
./node_modules/react-native/packager/packager.sh --root node_modules/react-native-webpack-server/_entry
```

The way command line options got parsed changed. This commit fixed it https://github.com/facebook/react-native/commit/769efdfcefd55cfed4fc16752e06bea1e7604a00#diff-75e3fc051b7c5100b4681e8a8f62615b

**Comment by grabbou** [comment]
Ah nice. Thanks ;)

**Comment by mjohnston** [comment]
Thanks @amccloud for digging into this one!

**Comment by gaearon** [comment]
If somebody stumbles here like I did, the idea is that you should either use 0.4.x or jump straight to 0.6 (which is currently only available as 0.6.0-rc).

**Comment by grabbou** [comment]
Or you can always edit source code (highly unrecommended, but kinda works till 0.6 goes stable)

**Comment by mjohnston** [comment]
I wonder if I should update the react-native peer dep to exclude 0.5.0? (>=0.4.0 <0.5.0 || >=0.6.0)

Also curious that there hasn't been a patch release for the packager fix...

**Comment by gaearon** [comment]
Yeah updating peerDep would be nice. If you do please include RC as a temporary measure (peerDeps need to include pre-releases explicitly AFAIK).

**Comment by mjohnston** [comment]
Done in 6af2618

**Comment by gaearon** [comment]
:+1: thanks!
