### ISSUE TITLE
“An SSL error has occurred” on Xcode 7 beta

### ISSUE THREAD

**Issue by gaearon** [mjohnston/react-native-webpack-server#35]
I'm not sure “whose” issue this really is but I'll leave this here for posterity. Someone might google this problem and come to this issue.

After trying to run an existing project on Xcode 7 beta on El Capitan Beta 2, I got this error:

> Could not connect to development server. Ensure node server is running <...>
> 
> An SSL error has occurred and a secure connection to the server cannot be made.

![screen shot 2015-06-28 at 03 34 17](https://cloud.githubusercontent.com/assets/810438/8394572/d132b01a-1d46-11e5-983f-9ac5fc52f908.png)

In the console, I got this:

```
CFNetwork SSLHandshake failed (-9806)
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9806)
```

A post in [this thread](https://forums.developer.apple.com/thread/4017) offered a workaround that I used:
1. Open `Info.plist`
2. Add these lines to it:

``` xml
<key>NSAppTransportSecurity</key>  
<dict>  
<key>NSAllowsArbitraryLoads</key>  
<true/>  
</dict>
```

This is probably a temporary workaround but it was good enough for me.
Please close if this is irrelevant to this repo.

**Comment by mjohnston** [comment]
As of iOS 9, all requests will be upgraded to TLS unless opted out. You can opt out globally as in Dan's comment, or on a per domain basis. For more info see http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

I wouldn't be surprised if localhost becomes a default exception by the iOS 9 GM.

**Comment by gaearon** [comment]
So.. should we add this to Info.plist of examples? I wasted an hour on this issue again because I forgot about it, and examples don't run as is.

**Comment by mjohnston** [comment]
At the very least we should add the localhost exception in the examples. @elliottsj?
