### ISSUE TITLE
CPU goes to +200% 

### ISSUE THREAD

**Issue by carlyeah** [mjohnston/react-native-webpack-server#36]
Everytime I run npm start script, take some seconds for the fans to start moving. Activity monitor shows a cpu use of +200%. Is this normal at this moment of the project?

**Comment by mjohnston** [comment]
Haven't seen this myself. What is the process name that is taking 200%... assuming `node`?

Do you see the same thing with the default react-native packager?

**Comment by carlyeah** [comment]
no, the common react-native packager worked just well. But I wanna add that today I upgrade OSX to last version of Yosemite, and it's working great again. Not sure what happen!

Sorry for the inconvenience !

**Comment by mjohnston** [comment]
Interesting though. Thanks for the report, will keep an eye out for this.

**Comment by grabbou** [comment]
Try disabling `hot-reload`. Reduced CPU usage at least 10 times :)

**Comment by osdio** [comment]
yes, I run `npm run hot` it takes about 140% cpu.
