### ISSUE TITLE
Stuck on Step 2 of Setup

### ISSUE THREAD

**Issue by geirman** [mjohnston/react-native-webpack-server#41]
I get stuck on this step...

> By default React Native will look for an index.ios.js at the root of the project. Delete this file and add an entry in your webpack config:

There's two things I don't really understand about this step...
1. Do you really want me to delete my index.ios.js file or delete a reference to that file in the webpack.config? 
2. I cannot find the webpack.config file. Should I expect to find it in my root?

**Comment by danscan** [comment]
@geirman I suggest using this as a template: https://github.com/mjohnston/react-native-webpack-server/blob/master/Examples/BabelES6/webpack.config.js

**Comment by elliottsj** [comment]
@geirman Were you able to set up your project? Closing for now
