### ISSUE TITLE
package.json not found in any of the roots

### ISSUE THREAD

**Issue by burgalon** [mjohnston/react-native-webpack-server#44]
When trying to set up environment similar to BabelES6 example, I'm getting the follow error when running `npm run start`:

<pre>
Error: File /Users/burg/git/home/node_modules/react-native-webpack-server/package.json not found in any of the roots
    at Fastfs._getAndAssertRoot (/Users/burg/git/home/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:137:13)
    at Fastfs._add (/Users/burg/git/home/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:152:10)
    at /Users/burg/git/home/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:38:18
    at Array.forEach (native)
    at /Users/burg/git/home/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:31:13
    at tryCallOne (/Users/burg/git/home/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/burg/git/home/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/burg/git/home/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
</pre>

Here is my `package.json`:

<pre>
{
  "name": "home",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "__commented__original_start": "node_modules/react-native/packager/packager.sh",
    "start": "node node_modules/react-native-webpack-server/bin/react-native-webpack-server.js start",
    "hot": "HOT=1 node node_modules/react-native-webpack-server/bin/react-native-webpack-server start --hot"
  },
  "dependencies": {
    "react": "^0.13.3",
    "react-native": "^0.7.1"
  },
  "devDependencies": {
    "babel": "^5.8.3",
    "babel-core": "^5.8.3",
    "babel-loader": "^5.3.2",
    "react-hot-loader": "^1.2.8",
    "react-native-webpack-server": "^0.2.2",
    "webpack": "^1.10.5",
    "webpack-dev-server": "^1.10.1"
  }
}
</pre>

My `webpack.config.js`

<pre>
var fs = require('fs');
var path = require('path');
var webpack = require('webpack');

var config = {

    debug: true,

    devtool: 'source-map',

    entry: {
        'index.ios': ['./src/main.js'],
    },

    output: {
        path: path.resolve(__dirname, 'build'),
        filename: '[name].js',
    },

    module: {
        loaders: [
            {test: /\.js$/, exclude: /node_modules/, loaders: ['babel?stage=0&blacklist=validation.react']},
        ],
    },

    plugins: [],

};

// Hot loader
if (process.env.HOT) {
    config.devtool = 'eval'; // Speed up incremental builds
    config.entry['index.ios'].unshift('./node_modules/react-native-webpack-server/hot/entry');
    config.entry['index.ios'].unshift('webpack/hot/only-dev-server');
    config.entry['index.ios'].unshift('webpack-dev-server/client?http://localhost:8082');
    config.output.publicPath = 'http://localhost:8082/';
    config.module.loaders[0].loaders.unshift('react-hot');
    config.plugins.unshift(new webpack.HotModuleReplacementPlugin());
}

// Production config
if (process.env.NODE_ENV === 'production') {
    config.plugins.push(new webpack.optimize.OccurrenceOrderPlugin());
    config.plugins.push(new webpack.optimize.UglifyJsPlugin());
}

module.exports = config;
</pre>

**Comment by MikaelCarpenter** [comment]
I'm also getting the same error, but using the CoffeeScript example.

**Comment by elliottsj** [comment]
In `package.json`, all you should need is

``` js
...
"scripts": {
  "start": "react-native-webpack-server start"
}
...
```

And in `webpack.config.js`:

``` js
...
// Hot loader
if (process.env.HOT) {
  config.devtool = 'eval'; // Speed up incremental builds
  config.entry['index.ios'].unshift('react-native-webpack-server/hot/entry');
  config.entry['index.ios'].unshift('webpack/hot/only-dev-server');
  config.entry['index.ios'].unshift('webpack-dev-server/client?http://localhost:8082');
  config.output.publicPath = 'http://localhost:8082/';
  config.module.loaders[0].loaders.unshift('react-hot');
  config.plugins.unshift(new webpack.HotModuleReplacementPlugin());
}
...
```

I've also updated the example projects so they don't depend on react-native-webpack-server to be in the upper directory: https://github.com/mjohnston/react-native-webpack-server/pull/56
