### ISSUE TITLE
Cannot resolve module 'react/lib/ReactMount'

### ISSUE THREAD

**Issue by AbrahamAlcaina** [mjohnston/react-native-webpack-server#45]
Hi, 

Went I tried to execute the hot loader I received: 

`Cannot resolve module 'react/lib/ReactMount'`

I use react-native 0.8.0 with [issue #40 patch](https://github.com/mjohnston/react-native-webpack-server/issues/40#issuecomment-123957667). 

But something in the entry.js is not working.

``` javascript
if (module.hot) {
    var ReactNativeMount = require('ReactNativeMount');
  var HotLoaderInjection = require('react-hot-loader/Injection');
  HotLoaderInjection.RootInstanceProvider.injectProvider({
    getRootInstances: function() {
      return ReactNativeMount._instancesByContainerID;
    }
  });
  //! Terrible hack to marshall WS messages onto React Native's event loop.
  setInterval(function() {}, 200);
}
```

Anybody have te same issue? or any ideas?

**Comment by danscan** [comment]
You have to install `react` (in addition to `react-native`) as a dev dependency as well.

**Comment by elliottsj** [comment]
@AbrahamAlcaina Did installing `react` solve your issue? Closing for now

**Comment by bairisuresh** [comment]
getting same error

**Comment by basslagter** [comment]
@bairisuresh you probably running an old version of 'react-hot-loader'. Update this module to version >= 3 and you should be fine.

**Comment by rivz-a** [comment]
Thank you very much! This is a working option
