### ISSUE TITLE
Add 0.9.0-rc support

### ISSUE THREAD

**Issue by ghost** [mjohnston/react-native-webpack-server#47]
I think that there is no need to code changes, just add composer.json support for react-native 0.9.0-rc

This is very important because since 0.9.0 rc TextInput is finally a true controlled component.

Thanks again for your work!

**Comment by mattiamanzati** [comment]
Also For 0.10.0 please!

**Comment by gaearon** [comment]
The best way to get support for something is to submit a PR. Just sayin' :-)
