### ISSUE TITLE
Sever crashes if request comes in before packager server starts

### ISSUE THREAD

**Issue by amccloud** [mjohnston/react-native-webpack-server#53]
It is a race. We could swallow the exception which is not ideal. I'd rather wait till both the webpack and packager servers start before the main server is started. To do that we'll need https://github.com/facebook/react-native/issues/2518

**Comment by elliottsj** [comment]
Hmm, I've just noticed that the react packager does provide a `.middleware()` function we could use instead of shelling out `packager.sh`: https://github.com/facebook/react-native/tree/master/packager#reactpackagermiddlewareoptions

That could be what we need

**Comment by amccloud** [comment]
@elliottsj the middleware is nice but we it excludes quite a bit of functionality like opening stack frame in editor and opening the dev tools,

**Comment by elliottsj** [comment]
Fixed by #60
