### ISSUE TITLE
Module Build Failed. Did you mean "react"

### ISSUE THREAD

**Issue by peterpme** [mjohnston/react-native-webpack-server#54]
![image](https://cloud.githubusercontent.com/assets/1211905/9620562/02005f4e-50e1-11e5-9b80-8a69500cd648.png)

Upgrading to latest webpack-server & 0.11.0-rc:

```
ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module build failed: SyntaxError: /Users/peter/Sites/wayv_react_native/node_modules/react-native/Libraries/react-native/react-native.js: Line 20: Did you mean "react"?
  18 | //   var ReactNative = {...require('React'), /* additions */}
  19 | //
> 20 | var ReactNative = Object.assign(Object.create(require('React')), {
```

**Comment by amccloud** [comment]
Try `npm install react-native-webpack-server@0.4.0-rc`

**Comment by amccloud** [comment]
You'll also want to make sure babel is configured with "blacklist": ["validation.react"]

**Comment by peterpme** [comment]
I'll try this tonight. Thanks!

**Comment by peterpme** [comment]
Worked, thanks!

**Comment by ptmt** [comment]
Thanks a lot, adding `blacklist: ["validation.react"]` helps a lot in upgrading to https://github.com/mjohnston/react-native-webpack-server/pull/64. I just not exluding any library for babel-loader and it works again. Should it be mentioned on `Readme.md` and Examples?

**Comment by gaearon** [comment]
@ptmt 

I wasn't sure why it was there—should we add it back? Please send a PR if it helps! (You can add `blacklist` to `query` object instead of the string now.)
