### ISSUE TITLE
Use React Transform instead of React Hot Loader

### ISSUE THREAD

**Issue by gaearon** [mjohnston/react-native-webpack-server#55]
[React Transform](https://github.com/gaearon/babel-plugin-react-transform) is a Babel plugin for applying runtime transformations to React classes. Combined with [react-transform-webpack-hmr](https://github.com/gaearon/react-transform-webpack-hmr), it replaces React Hot Loader completely.
- [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate/)
- [example of porting react-hot-loader project to react-transform](https://github.com/gaearon/flux-react-router-example/commit/53e5ad5ec10974d195b002a3a07a3239d1478b7b)

Benefits:
- No need to work around dependency on `react/lib/ReactMount`
- Does not depend on `react` package: you can give it `react-native` in configuration just fine
- Better works with ES6 features like getters, and is much more stable
- Allows other transformations, e.g. [react-transform-catch-errors](https://github.com/gaearon/react-transform-catch-errors)

**Comment by amccloud** [comment]
@gaearon will give it a shot this weekend

**Comment by ptmt** [comment]
+1. @amccloud if you don't mind I could help with that. Do you have any progress?

**Comment by amccloud** [comment]
I do not have any progress yet.

**Comment by gaearon** [comment]
FYI—I'm on it.

**Comment by gaearon** [comment]
@elliottsj I'm having some super weird issues working on it—any chance you could give me a few minutes on Slack?

**Comment by davecoates** [comment]
@gaearon - I had something working on the weekend for this but I'm getting errors trying again now (Uncaught SyntaxError: Unexpected reserved word) - I swear nothing changed! In case it helps you:  https://github.com/davecoates/react-native-webpack-server/tree/react-transform

My .babelrc

```
{
  "env": {
    "stage": 0,
    "development": {
      "plugins": [
        "react-transform"
      ],
      "extra": {
        "react-transform": [
        {
          "target": "react-transform-webpack-hmr",
          "imports": ["react-native"],
          "locals": ["module"]
        },
         {
          "target": "react-transform-catch-errors",
          "imports": ["react-native", "./src/ErrorReporter"]
        }
        ]
      }
    }
  }
}
```

Relevant part of webpack.config.js

```
if (process.env.HOT) {
  config.devtool = 'inline-source-map'; // Speed up incremental builds
  config.entry['index.ios'].unshift('webpack-hot-middleware/client?path=http://localhost:8080/__webpack_hmr');
  config.output.publicPath = 'http://localhost:8080/';
  config.plugins.unshift(new webpack.HotModuleReplacementPlugin());
}

```

**Comment by gaearon** [comment]
Please see https://github.com/mjohnston/react-native-webpack-server/pull/64 and test it on your projects!
