### ISSUE TITLE
Cannot Resolve Module 'React'

### ISSUE THREAD

**Issue by peterpme** [mjohnston/react-native-webpack-server#58]
file:
`import connectToStores from 'alt/utils/connectToStores'`

terminal:

``` javascript
ERROR in ./~/alt/utils/connectToStores.js
Module not found: Error: Cannot resolve module 'react' in /sites/node_modules/alt/utils
 @ ./~/alt/utils/connectToStores.js 56:13-29
```

webpack:

`````` javascript
  resolve: {
    extensions: ['', '.js'],
    root: [
      path.join(__dirname, './node_modules'),
      path.join(__dirname, './src'),
    ]
  },```

``````

react-native 0.11.0-rc
react-native-webpack-server 0.40.-rc
webpack 1.10.1
alt 0.17.1

```
```

**Comment by amccloud** [comment]
Not sure if you need the root config.

Looks like alt may not work with react-native. It is trying to require things like Component from react instead of react-native. You could try to alias react to react-native.

``` javascript
  resolve: {
    alias: {
      'react': 'react-native'
    }
  }
```

**Comment by peterpme** [comment]
Hey, thank you for the quick reply!
- Out of curiosity, why wouldn't I need the root config? 
- Alt works OOTB when I try `import alt from 'alt`. That's all fine. 
- The issue occurs when I try to import a utils file that lives inside alt, `'alt/utils/connectToStores'`
- I will try that!

Thanks again

**Comment by amccloud** [comment]
- I've never had to do that while using webpack.
- That specific Alt util requires from `react` and not `react-native`https://github.com/goatslacker/alt/blob/master/src/utils/connectToStores.js#L46
- There are probably other instances where Alt requires `react` https://github.com/goatslacker/alt/search?utf8=%E2%9C%93&q=%22import+React+from+%27react%27%22&type=Code

**Comment by peterpme** [comment]
Alt works fine with React Native though. React Native uses React under the hood so it's a common dependency we're already using. I'm going to try this same scenario in a non React-Native environment and see what happens.

**Comment by amccloud** [comment]
I don't believe that is not true yet. See https://github.com/facebook/react-native/blob/master/package.json

**Comment by peterpme** [comment]
Hm you might be right. In either case, alt works fine. I am going to look into this issue further and try the `alias` step you provided. I think that's a great idea. 

Thanks again!

**Comment by amccloud** [comment]
@ppiekarczyk I ran into the same issue with relay https://github.com/facebook/relay/issues/26

**Comment by peterpme** [comment]
This worked, thank you!
