### ISSUE TITLE
image! require error

### ISSUE THREAD

**Issue by boyswan** [mjohnston/react-native-webpack-server#6]
Firstly thank you for this, it's great!

The only problem I've had is requiring images via Image.xcassets.  Is there currently a way to handle this?

**Comment by mjohnston** [comment]
Let me know if this works for you: https://github.com/willpiers/react-native-image-loader

**Comment by mjohnston** [comment]
There doesn't appear to be documentation there, but I imagine you would have to rewrite the require statement in your code to something like:

``` js
require('my_image.png');
```

And in your webpack config:

``` js
modules: {
  loaders: [
    {test: /\.png$/, loaders: ['react-native-image']}
  ]
}
```

The loader would transform your code to:

``` js
require('image!my_image');
```

**Comment by colinhicks** [comment]
@boyswan, your issue sounds familiar. If @mjohnston's suggestion isn't what you need, would you mind giving my changes in #7 a spin?

**Comment by boyswan** [comment]
@mjohnston thanks, has no compile errors however doesn't display the image. @colinhicks #7 works perfectly! Thanks

**Comment by MoOx** [comment]
@mjohnston I am currently looking for a react native like webpack loader for image since I use [react-native-web](https://github.com/necolas/react-native-web) but your previous link https://github.com/willpiers/react-native-image-loader is a 404 for me. Any idea where I can find this thing?
