### ISSUE TITLE
Incompatibility with React native 0.11.0

### ISSUE THREAD

**Issue by OssamaZ** [mjohnston/react-native-webpack-server#62]
`
ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ActivityIndicatorIOS' ..
`

**Comment by OssamaZ** [comment]
ok, done i just saw the update in npm.

**Comment by elliottsj** [comment]
Awesome! I've just updated the example projects too to work with RN 0.11 and react-native-webpack-server 0.4.0.
