### ISSUE TITLE
Starting the BabelES6 example with no modifications I get an error

### ISSUE THREAD

**Issue by duro** [mjohnston/react-native-webpack-server#68]
![iphone_6_-_iphone_6___ios_9_0__13a340_](https://cloud.githubusercontent.com/assets/17632/9947504/76c34b82-5d4f-11e5-8e02-3618e8f47064.png)

Any ideas?

**Comment by duro** [comment]
All I did was clone repo, run `npm run hot` and run project in XCode

**Comment by OssamaZ** [comment]
Dismiss the error message, cmd+D and activate debug in chrome option, reload your js.

**Comment by duro** [comment]
Sweet. That did it.

**Comment by gaearon** [comment]
Duplicate of https://github.com/mjohnston/react-native-webpack-server/issues/2.

Can we catch this early and provide a better error message?

**Comment by OssamaZ** [comment]
Agreed. the error is so common, it needs a better descriptive message.

**Comment by elliottsj** [comment]
Here's a quick fix: https://github.com/mjohnston/react-native-webpack-server/pull/69
