### ISSUE TITLE
Quick Question: Why Webpack and Hot Loader and not just built in react-native live reload?

### ISSUE THREAD

**Issue by duro** [mjohnston/react-native-webpack-server#70]
I'm just curious what your option on this is? I am very used to using Webpack and Hot Loading in the browser, so I assumed I needed it for react-native. But now I have discovered that the vanilla React-Native starter includes a live reload feature. Is there something different about these approaches?

**Comment by gaearon** [comment]
From what I know, live reloading in React Native relaunches your app. This means you lose the state of your app and your component tree unless you're doing something special to persist it.

**Comment by duro** [comment]
Got it. Thanks!
