### ISSUE TITLE
Better Source Maps?

### ISSUE THREAD

**Issue by duro** [mjohnston/react-native-webpack-server#71]
I read the README about source maps, but I'm a little confused. Is it possible to get clean source maps in the debugger when using Webpack dev server? Right now I am still seeing the transpiled Webpack code.

**Comment by elliottsj** [comment]
Using `config.devtool = 'eval';` (like in the [BabelES6 example](https://github.com/mjohnston/react-native-webpack-server/blob/4dc2a54fe8a8c022a4b0a5eff86666117a00452a/Examples/BabelES6/webpack.config.js#L38)), you can view your source code in Chrome:

<img width="931" alt="screenshot 2015-09-17 20 37 45" src="https://cloud.githubusercontent.com/assets/2177366/9949544/11552fea-5d7c-11e5-9023-ec3a1c1193b7.png">

However this won't work with hot module replacement (https://github.com/mjohnston/react-native-webpack-server/issues/27); you must instead use the slower `config.devtool = 'source-map';`
