### ISSUE TITLE
Create new Server with webpack config object instead of path

### ISSUE THREAD

**Issue by timmh** [mjohnston/react-native-webpack-server#8]
Thank you very much for creating this, it's very useful!

However, I use a highly customized webpack project setup and it would be great to be able to pass a webpack config object instead of the webpack.config.js-path to `lib/Server.js`.
What do you think?

**Comment by mjohnston** [comment]
That makes sense, and seems like a fairly common use case.  I won't be at a computer today as I'm travelling but you're more than welcome to open a pull request and I can review it.

**Comment by mjohnston** [comment]
This was fixed in https://github.com/mjohnston/react-native-webpack-server/pull/9
