### ISSUE TITLE
Execute `npm run hot` with xcode when clicking on `Build and run`

### ISSUE THREAD

**Issue by JeanLebrument** [mjohnston/react-native-webpack-server#94]
Hello,

I was wondering where can modify the script executed when I click on `Build and Run` on XCode? 

I was thinking in that it was a script executed in `Build Phases > Run Script Phase`, but I didn't found any.

Any suggestion?

Best,
Jean

**Comment by elliottsj** [comment]
You can find the script in **Libraries/React.xcodeproj -> Build Phases -> Run Script**, e.g.
<img width="1198" alt="screenshot 2015-10-09 18 45 06" src="https://cloud.githubusercontent.com/assets/2177366/10407220/f3c02854-6eb5-11e5-9f91-7e3a688e025f.png">

**Comment by JeanLebrument** [comment]
Great, thanks!
