### ISSUE TITLE
Selective Loading

### ISSUE THREAD

**Issue by clintandrewhall** [mjohnston/react-native-webpack-server#96]
I'm using a library that apparently uses selective loading to determine which JS files to load, e.g. it has a <file>.ios.js and <file>.android.js file.  This appears to be tripping up webpack on require.  This feels like a big deal to workaround, but I was curious if you had run into something like this yet.

https://github.com/xinthink/react-native-material-kit

**Comment by elliottsj** [comment]
This feature is being tracked in #120
