### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by nc** [mjohnston/react-native-webpack-server#99]
Fresh react-native 0.12 project. Add server and running off master a58a670fe9b68b88da3b980da55390b85bba7ed9

`Uncaught Error: Uncaught ReferenceError: document is not definedmessageHandlers.executeApplicationScript @ debuggerWorker.js:18onmessage @ debuggerWorker.js:42`

**Comment by nc** [comment]
Traced to `var scriptElements = document.getElementsByTagName("script");`

**Comment by auser** [comment]
Ditto

**Comment by elliottsj** [comment]
I've traced the error to [webpack-dev-server/client/index.js#L4](https://github.com/webpack/webpack-dev-server/blob/c52035ef0664fecc74a4a0dc481e39c523426f88/client/index.js#L4), which is [included as `'webpack-dev-server/client?http://localhost:8082'` in the webpack config](https://github.com/mjohnston/react-native-webpack-server/blob/42a2d29cf7a6a98318fe5dfd4a537be8c623a811/Examples/BabelES6/webpack.config.js#L41).

I think I know how to get HMR working with the new web worker in RN 0.12 (at least in a hacky way). More info soon :smile:

**Comment by elliottsj** [comment]
See #103 for the full explanation & temporary fix
